FROM debian:trixie-slim

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing \
  && apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  gnupg \
  && apt-get clean

RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update --fix-missing \
  && apt-get install -y --no-install-recommends \
  nodejs \
  && apt-get clean

COPY image-processor/pkg /image-processor/pkg
COPY app /app
WORKDIR /app
RUN npm install
